# pandas DataFrame

In [1]:
import pandas as pd

In [2]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
    If ``data`` is DataFrame then is ignored.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {"col1": [1, 2], "col2": [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {"col1": [0, 1, 2, 3], "col2": pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(
...     np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=["a", "b", "c"]
... )
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array(
...     [(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...     dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")],
... )
>>> df3 = pd.DataFrame(data, columns=["c", "a"])
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3
File:           d:\anaconda\envs\python_env\lib\site-packages\pandas\__init__.py
Type:           type
Subclasses:     SubclassedDataFrame

In [3]:
students = {'Name': ['Vishnu', 'Ram', 'Joseph', 'Abdul'],
            'Grades': [48, 65, 99, 88]}

In [4]:
pd.DataFrame(data=students)

     Name  Grades
0  Vishnu      48
1     Ram      65
2  Joseph      99
3   Abdul      88

In [5]:
# Create a DataFrame with two columns: 1. Employee Name 2. Employee Salary
employee_info = {'Name': ["Kumar", "Anandan", "Rajendran", "Mohammed", "Arogyaswami"],
                 'Salary': [25000, 45000, 66000, 50000, 25000]}

In [6]:
employees = pd.DataFrame(employee_info)
employees

          Name  Salary
0        Kumar   25000
1      Anandan   45000
2    Rajendran   66000
3     Mohammed   50000
4  Arogyaswami   25000

## Indexing

In [7]:
employees.loc[2, 'Salary']  # Extract Rajendran's Salary

np.int64(66000)

In [8]:
employees.iloc[4, 1]  # Extract Arogyaswami's Salary

np.int64(25000)

## Slicing

In [9]:
employees

          Name  Salary
0        Kumar   25000
1      Anandan   45000
2    Rajendran   66000
3     Mohammed   50000
4  Arogyaswami   25000

In [10]:
employees.loc[2:3, 'Salary']  # Extract Rajendran and Mohammed's salary only

2    66000
3    50000
Name: Salary, dtype: int64

In [11]:
employees.iloc[2:4, 1]

2    66000
3    50000
Name: Salary, dtype: int64

In [12]:
employees.loc[[0, 4], ['Name', 'Salary']]  # Fancy Indexing | Extract Kumar and Arogyaswami's details

          Name  Salary
0        Kumar   25000
4  Arogyaswami   25000

In [13]:
employees.iloc[[0, 4], [0, 1]]

          Name  Salary
0        Kumar   25000
4  Arogyaswami   25000

In [14]:
employees.loc[2:3, ['Name', 'Salary']]  # Combination of slicing + fancy indexing

        Name  Salary
2  Rajendran   66000
3   Mohammed   50000

In [15]:
employees.iloc[2:4, [0, 1]]

        Name  Salary
2  Rajendran   66000
3   Mohammed   50000

## Add a new column

In [16]:
employees

          Name  Salary
0        Kumar   25000
1      Anandan   45000
2    Rajendran   66000
3     Mohammed   50000
4  Arogyaswami   25000

In [17]:
employees['Department'] = ['Marketing', 'Sales', 'Marketing', 'Technical', 'Sales']

In [18]:
employees

          Name  Salary Department
0        Kumar   25000  Marketing
1      Anandan   45000      Sales
2    Rajendran   66000  Marketing
3     Mohammed   50000  Technical
4  Arogyaswami   25000      Sales

In [19]:
employees['ID'] = ['E001', 'E005', 'E425', 'E666', 'E778']

In [20]:
employees

          Name  Salary Department    ID
0        Kumar   25000  Marketing  E001
1      Anandan   45000      Sales  E005
2    Rajendran   66000  Marketing  E425
3     Mohammed   50000  Technical  E666
4  Arogyaswami   25000      Sales  E778

In [21]:
employees.iloc[2]

Name          Rajendran
Salary            66000
Department    Marketing
ID                 E425
Name: 2, dtype: object

In [22]:
employees.iloc[2, :]

Name          Rajendran
Salary            66000
Department    Marketing
ID                 E425
Name: 2, dtype: object

In [23]:
employees = employees.set_index('ID')  # Set ID as index for easy access of employees records

In [24]:
employees

             Name  Salary Department
ID
E001        Kumar   25000  Marketing
E005      Anandan   45000      Sales
E425    Rajendran   66000  Marketing
E666     Mohammed   50000  Technical
E778  Arogyaswami   25000      Sales

In [25]:
employees.loc['E425']

Name          Rajendran
Salary            66000
Department    Marketing
Name: E425, dtype: object

In [26]:
employees['hike'] = [0.2, 0.3, 0.10, 0.40, 0.05]

In [27]:
employees

             Name  Salary Department  hike
ID
E001        Kumar   25000  Marketing  0.20
E005      Anandan   45000      Sales  0.30
E425    Rajendran   66000  Marketing  0.10
E666     Mohammed   50000  Technical  0.40
E778  Arogyaswami   25000      Sales  0.05

In [28]:
employees['package'] = (employees['Salary'] * 12) * (1 + employees['hike'])
employees

             Name  Salary Department  hike   package
ID
E001        Kumar   25000  Marketing  0.20  360000.0
E005      Anandan   45000      Sales  0.30  702000.0
E425    Rajendran   66000  Marketing  0.10  871200.0
E666     Mohammed   50000  Technical  0.40  840000.0
E778  Arogyaswami   25000      Sales  0.05  315000.0

In [29]:
# employees['package'] = (employees['salary'] * 12) + (employees['salary'] * 12 * employees['hike'])
                                        # x          +              x      * y
                                    # x *  [ 1 + y]  = x + x * y

# (employees['salary'] * 12) * (1 + employees['hike']) -> Simplified version

In [30]:
employees['Manager'] = employees['Department'].map({'Marketing': 'Suresh', 'Technical': 'Ganesh', 'Sales': 'Rajesh'})
employees

             Name  Salary Department  hike   package Manager
ID
E001        Kumar   25000  Marketing  0.20  360000.0  Suresh
E005      Anandan   45000      Sales  0.30  702000.0  Rajesh
E425    Rajendran   66000  Marketing  0.10  871200.0  Suresh
E666     Mohammed   50000  Technical  0.40  840000.0  Ganesh
E778  Arogyaswami   25000      Sales  0.05  315000.0  Rajesh

In [31]:
def package_category(package):
    if package < 300000:
        return "Bronze"
    elif 300000 <= package <= 600000:
        return "Silver"
    else:
        return "Gold"

In [32]:
employees['Package Category'] = employees['package'].apply(package_category)
employees

             Name  Salary Department  hike   package Manager Package Category
ID
E001        Kumar   25000  Marketing  0.20  360000.0  Suresh           Silver
E005      Anandan   45000      Sales  0.30  702000.0  Rajesh             Gold
E425    Rajendran   66000  Marketing  0.10  871200.0  Suresh             Gold
E666     Mohammed   50000  Technical  0.40  840000.0  Ganesh             Gold
E778  Arogyaswami   25000      Sales  0.05  315000.0  Rajesh           Silver

In [33]:
## Create a new column "Bonus Type". The column is based on "hike" column. 
# If hike is more than 50%, it should return "Senior"
# If hike is between 25% and 50%, it should return "Mid-leveL"
# If hike is less than 25%, it should return "Junior"

## Save a DataFrame as a `.csv` file

In [34]:
employees.to_csv("employees.csv")  # comma separated values (.csv) file

In [37]:
employee_info = pd.read_csv("employee_data.csv")   # Load a .csv file into a pandas DataFrame

In [38]:
employee_info.head()  # Dispaly only the first 5 rows by default

,employee_id,name,date_of_birth,hire_date,department,gender,salary,city,email,age
0,201,Emma Johansson,3/15/1985,6/1/2015,Engineering,Female,85000.0,Stockholm,emma.johansson@ericsson.com,41
1,202,Noah Williams,7/22/1990,3/15/2018,Marketing,Male,62000.0,London,noah.williams@unilever.com,35
2,203,Chloe Dubois,4/18/1992,9/1/2017,Sales,Female,58000.0,Lyon,chloe.dubois@loreal.com,34
3,204,James Carter,11/30/1982,4/1/2010,NaN,Male,NaN,New York,james.carter@jpmorgan.com,43
4,205,Sofia Mendes,5/10/1995,1/10/2021,HR,Female,54000.0,Sao Paulo,sofia.mendes@embraer.com,30

In [41]:
employee_info.tail(3)   # Display the last 3 rows of the DataFrame

,employee_id,name,date_of_birth,hire_date,department,gender,salary,city,email,age
17,218,Amara Diallo,8/15/1996,1/10/2023,HR,Female,49000.0,Dakar,NaN,29
18,219,Lucas Dupont,12/5/1983,11/1/2009,Finance,MALE,88000.0,Paris,lucas.dupont@airbus.com,42
19,220,Mia Andersen,9/27/1995,5/14/2022,Marketing,Female,63000.0,Copenhagen,mia.andersen@maersk.com,30

## Inspecting the DataFrame

In [42]:
employee_info.info()  # Information about data type of columns and null values in each column

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    20 non-null     int64
 1   name           20 non-null     str
 2   date_of_birth  20 non-null     str
 3   hire_date      20 non-null     str
 4   department     17 non-null     str
 5   gender         20 non-null     str
 6   salary         18 non-null     float64
 7   city           20 non-null     str
 8   email          18 non-null     str
 9   age            20 non-null     int64
dtypes: float64(1), int64(2), str(7)
memory usage: 3.0 KB

In [43]:
employee_info = employee_info.set_index("employee_id")  # Set `employee_id` as the index

In [45]:
employee_info.head(2)

,name,date_of_birth,hire_date,department,gender,salary,city,email,age
employee_id,,,,,,,,,
201,Emma Johansson,3/15/1985,6/1/2015,Engineering,Female,85000.0,Stockholm,emma.johansson@ericsson.com,41
202,Noah Williams,7/22/1990,3/15/2018,Marketing,Male,62000.0,London,noah.williams@unilever.com,35

In [47]:
employee_info['department'].value_counts()  # Raw counts in each category

department
Engineering    4
Marketing      4
Sales          3
HR             3
Finance        3
Name: count, dtype: int64

In [48]:
employee_info['department'].value_counts(normalize=True)  # Proportion in each category (out of total)

department
Engineering    0.235294
Marketing      0.235294
Sales          0.176471
HR             0.176471
Finance        0.176471
Name: proportion, dtype: float64

In [49]:
employee_info['department']

employee_id
201    Engineering
202      Marketing
203          Sales
204            NaN
205             HR
206        Finance
207    Engineering
208          Sales
209            NaN
210        Finance
211      Marketing
212             HR
213    Engineering
214    Engineering
215          Sales
216      Marketing
217            NaN
218             HR
219        Finance
220      Marketing
Name: department, dtype: str

In [61]:
type(employee_info['department'].unique()[3])

float

In [63]:
x = 3
y = 3
x is y

True

In [67]:
id(x)

140724656972776

In [68]:
id(y)

140724656972776

In [71]:
import numpy as np

def assign_category(department):
    if department is np.nan:
        return "Unassigned"
    else:
        return department

employee_info['department'] = employee_info['department'].apply(assign_category)
employee_info['department'].value_counts(normalize=True)

department
Engineering    0.20
Marketing      0.20
Sales          0.15
Unassigned     0.15
HR             0.15
Finance        0.15
Name: proportion, dtype: float64

In [ ]:
## Change the null values in email column to "Unassigned"

In [77]:
# Replace null values with average/median value. Imputing null values
median_salary = employee_info['salary'].median()
employee_info['salary'] = employee_info['salary'].fillna(median_salary)

In [79]:
employee_info['salary'].dtype  # Numeric type

dtype('float64')

In [81]:
employee_info['salary'] = employee_info['salary'].astype('str')  # String type
employee_info['salary']

employee_id
201    85000.0
202    62000.0
203    58000.0
204    64000.0
205    54000.0
206    71000.0
207    90000.0
208    47000.0
209    65000.0
210    78000.0
211    64000.0
212    53000.0
213    82000.0
214    95000.0
215    51000.0
216    67000.0
217    60000.0
218    49000.0
219    88000.0
220    63000.0
Name: salary, dtype: str

In [82]:
employee_info['salary'].mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [83]:
employee_info['date_of_birth'].dtype  # string type

In [85]:
employee_info['date_of_birth'] = pd.to_datetime(employee_info['date_of_birth'])  # Converting into datetime object
employee_info['date_of_birth']

employee_id
201   1985-03-15
202   1990-07-22
203   1992-04-18
204   1982-11-30
205   1995-05-10
206   1988-08-04
207   1992-12-19
208   1997-09-11
209   1993-02-28
210   1987-09-17
211   1991-04-03
212   1989-06-25
213   1994-01-14
214   1986-10-09
215   1986-02-23
216   1990-07-31
217   1993-03-20
218   1996-08-15
219   1983-12-05
220   1995-09-27
Name: date_of_birth, dtype: datetime64[us]

In [87]:
year = employee_info['date_of_birth'].dt.year  # Extract year in date
month = employee_info['date_of_birth'].dt.month  # Extract month in date
day = employee_info['date_of_birth'].dt.day  # Extract day in date